frontend/main/main.py
from flask import Blueprint, render_template, request, redirect
#from flask import current_app as app

from sqlalchemy import Table, Column, Integer, func, sql, and_


from datetime import datetime

import sqlalchemy

from ..models import OrdenesCabecera, Todo, vResumenItemActual, vResumenItemAnterior , Registro
from ..models import vResumenOrdenesActual, rcPedidos, rdPedidos

from .. import db


main_bp = Blueprint('main_bp', __name__, template_folder='templates')

def fecha_sistema(): 
  return datetime.now().strftime("%d-%b-%Y, %I:%M %p")


@main_bp.route('/', methods=['POST', 'GET'])
def index():
    if request.method == 'POST':
    #    task_content = request.form['content']
    #    new_task = Todo(content=task_content)

        try:
            
    #        db.session.add(new_task)
    #        db.session.commit()
            return redirect('/')
        except:
            return 'Error adding'

    else:
        #tasks = Todo.query.order_by(Todo.date_created).all()
        return render_template('dashboard.html', fecha=fecha_sistema())



@main_bp.route('/delete/<int:id>')
def delete(id):
    task_to_delete = Todo.query.get_or_404(id)

    try:
        db.session.delete(task_to_delete)
        db.session.commit()
        return redirect('/')
    except:
        return 'Error deleting'


@main_bp.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):

    task = Todo.query.get_or_404(id)

    if request.method == "POST":
        task.content = request.form['content']
    else:
        return render_template('update.html', task=task)

    try:
        db.session.commit()
        return redirect('/')
    except:
        return 'Error updating'


@main_bp.route('/items', methods=['GET', 'POST'])
def items():

    resumen_ant = vResumenItemAnterior().query.first_or_404()
    resumen_act = vResumenItemActual().query.first_or_404()

    if request.method == "POST":
        #task.content = request.form['content']
        pass ;
    else:
        return render_template('inventario.html',  
                    antes=resumen_ant, actual=resumen_act )



@main_bp.route('/orders', methods=['GET', 'POST'])
def orders():

    ROWS_PER_PAGE = 20

    page = request.args.get('page',1, type=int)
    tab = request.args.get('tab', 1, type=int)
 
    resumen = vResumenOrdenesActual().query.first_or_404()

    tabla = None 

    if tab==1:
       tabla = db.session.query(OrdenesCabecera).filter(OrdenesCabecera.proc_status=="ok").order_by(OrdenesCabecera.fecha.desc()).paginate(page=page, per_page=ROWS_PER_PAGE)    

    if tab==2:
       tabla = db.session.query(OrdenesCabecera).filter(OrdenesCabecera.proc_status=="KO").order_by(OrdenesCabecera.fecha.desc()).paginate(page=page, per_page=ROWS_PER_PAGE)    

    if request.method == "POST":
        pass
    else:
        return render_template('ordenes.html', datos=resumen, tabla=tabla, tab=tab)



@main_bp.route('/cash', methods=['GET', 'POST'])
def cash():

    ROWS_PER_PAGE = 20
    page = request.args.get('page',1, type=int)
    tab = request.args.get('tab', 1, type=int)    

    # INI: se construyen los queries
    ped_reg = db.session.query(rcPedidos, Registro).join(Registro, and_ (rcPedidos.rcp_cia == Registro.rcp_cia   
                                                , rcPedidos.rcp_pedido == Registro.rcp_pedido), 
                                                isouter=True ).subquery()  

    q1 = db.session.query(ped_reg).filter(ped_reg.c.reg_estatus==None).subquery() #pendientes
    q2 = db.session.query(ped_reg).filter(ped_reg.c.reg_estatus=='OK').subquery() #aceptados
    q3 = db.session.query(ped_reg).filter(ped_reg.c.reg_estatus=='KO').subquery() #rechazados
    q4 = db.session.query(ped_reg).filter(ped_reg.c.reg_estatus!=None).subquery() #procesados

    # INI: se construyen los queries

    resumen = db.session.query(func.count(q1.c.rcp_pedido).label('cantidad'), 
                               func.sum(q1.c.rcp_monto).label('monto')
                               ).one_or_none()

    totl = resumen.cantidad or 0
    monto = resumen.monto or 0

    facs = db.session.query(q1).filter(q1.c.rcp_salida == 'FA').count()
    devs = db.session.query(q1).filter(q1.c.rcp_salida == 'NC').count()
    otrs = totl-facs-devs    

    antes = { 'totl':totl, 'facs':facs, 'devs':devs, 'otrs':otrs, 'monto':monto}

    #ok = db.session.query(Registro.rcp_pedido).filter(Registro.reg_estatus=='OK').count()
    ok  = db.session.query(q2).count()
    #ko = db.session.query(Registro.rcp_pedido).filter(Registro.reg_estatus=='KO').count()
    ko  = db.session.query(q3).count()
    fec = db.session.query(func.max(Registro.reg_fecha_modificacion).label('fec')).one_or_none().fec

    
    qry = None
    if tab ==1: qry = q1
    if tab ==2: qry = q2 
    if tab ==3: qry = q3 
    

    tabla = db.session.query(qry).order_by(qry.c.reg_fecha_creacion).paginate(page=page, per_page=ROWS_PER_PAGE)    

    mnt = db.session.query(func.sum(q4.c.rcp_monto).label('mnt')).one_or_none().mnt

    procs = ok+ko
    pends = totl - procs
    
    actual = { 'totl':procs, 'facs':ok, 'devs':ko, 'otrs':0,  'monto':mnt, 'fec':fec}
    #fec2 = db.session.query()


    if request.method == "POST":
        pass
        #task.content = request.form['content']
    else:
        return render_template('venta_contado.html', antes=antes, actual=actual, tabla=tabla, page=page, tab=tab, flag=False)


@main_bp.route('/credit', methods=['GET', 'POST'])
def credit():

    #task = Todo.query.get_or_404(id)

    if request.method == "POST":
        pass
        #task.content = request.form['content']
    else:
        return render_template('venta_credito.html', fecha=fecha_sistema())


frontend/update/routes.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

@admin.route('/')
def index():
	return "Hello, World! This is the admin page."

frontend/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

{% macro input(name, value='', type='text', size=20) -%}
    <input type="{{ type }}" name="{{ name }}" value="{{
        value|e }}" size="{{ size }}">
{%- endmacro %}

frontend/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--link rel="stylesheet" type="text/css" href="../static/css/bulma-min-0.4.0.css"/-->
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.0/css/bulma.css'>
    <link rel="stylesheet" type="text/css" href="../static/css/style.css"/>
    {% block head %}
    {% endblock %}
</head>

<body>
   
  <header class="hero is-primary">
        <div class="hero-head">
            <nav class="nav has-shadow">
                <div class="nav-left" >
                    <a href="https://momi.com.pa/" class="navbar-item is-selected">
                        <img src="{{ url_for('static', filename='images/momi-logo-footer_200x.png') }}" style="margin-top: 10px; margin-left: 5px;"  width="100px" alt="Momi: momentos felices"   >
                    </a>
                </div>
            
                <div class="nav-right nav-menu">
                            <a href="{{ url_for('main_bp.index') }}" class="nav-item is-tab">
                                Home
                            </a>
                            <a href="{{ url_for('auth_bp.login') }}" class="nav-item is-tab">
                                Login
                            </a>
                            <a href="{{ url_for('auth_bp.register') }}" class="nav-item is-tab">
                                Sign Up
                            </a>
                            <a href="{{ url_for('auth_bp.logout') }}" class="nav-item is-tab">
                                Logout
                            </a>
                </div>
            </nav>
        </div>
  </header>

  <div class="section">
      <div class="columns">
        <aside class="column is-2">
          <nav class="menu">
              <p class="menu-label">
                General
              </p>
              <ul class="menu-list">
                <li><a class="" href="/">Dashboard</a></li>
              </ul>
              <p class="menu-label">
                Administraci&oacute;n
              </p>
              <ul class="menu-list">
                <li>
                  <a class="">Bajar del ERP</a>
                  <ul>
                    <li><a href="/items">Inventario</a></li>
                    <li><a href="/orders">Ordenes</a></li>
                  </ul>
                </li>
              <p class="menu-label">
                Transacciones
              </p>
              <ul class="menu-list">
                <li>
                  <a class="">Subir al ERP</a>
                  <ul>
                    <li><a href="/cash">Venta Contado</a></li>
                    <li><a href="/credit">Venta Cr&eacute;dito</a></li>
                  </ul>
                </li>
            </ul>
        </aside>

        <main class="column">

          {% block content %}
          {% endblock %}
 
        </main>
      </div>
    </div>
         

</body>

</html>

frontend/templates/index.html
{% extends 'base.html' %}

{% block head %}
<title>Task Master</title>
{% endblock %}

{% block content %}

<h3 class="title">Registros</h3>
<div>
    <form class="column is-4 is-offset-4" action="/" method="POST">
            <div class="box">
                <div class="field">
                    <input class="input is-large" type="text" name="content" id="content" placeholder="Nota" autofocus>
                    <span class="pure-form-message-inline">*Campo obligatorio</span>
                </div>
            </div>
            <div>
                <br>
                <input type="submit" class="pure-button pure-button-primary" value="Add Task">
            </div>
    </form>
</div>


{% if tasks|length < 1 %} <h4> No hay registros. Cree el primero</h4>

    {% else %}
    <table class="pure-table">
        <thead>
            <tr>
                <th>Task</th>
                <th>Added</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr class="pure-table-odd">
                <td>{{ task.content }}</td>
                <td>{{ task.date_created.date() }} </td>
                <td>
                    <a href="/delete/{{ task.id }}">Delete</a>
                    <br>
                    <a href="/update/{{ task.id }}">Update</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

{% endblock %}

frontend/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

frontend/templates/register.html
{% from "_formhelpers.html" import render_field %}
<form method=post>
  <dl>
    {{ render_field(form.username) }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ render_field(form.confirm) }}
    {{ render_field(form.accept_tos) }}
  </dl>
  <p><input type=submit value=Register>
</form>

frontend/templates/signup.html
{% extends "base.html" %}


{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        <form method="POST" action="/register">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

frontend/templates/update.html
{% extends 'base.html' %}

{% block head %}
<title>Task Master</title>
{% endblock %}

{% block content %}
<div class="wrapper">
    <h3>Update Task</h3>
    <div class="form">
        <form action="/update/{{task.id}}" method="POST">
            <input type="text" name="content" id="content" value="{{task.content}}">
            <input type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock %}